version: "3.7"

services:
  moviebox-discovery-service:
    image: moviebox-discovery
    container_name: moviebox-discovery-container
    ports:
      - ${MOVIEBOX_DISCOVERY_HOST_PORT}:${MOVIEBOX_DISCOVERY_CONTAINER_PORT}
    networks:
      moviebox-network:
    restart: on-failure
  movie-service:
    image: movie-service
    networks:
      moviebox-network:
    ports:
      - ${MOVIE_SERVICE_HOST_PORT}:${MOVIE_SERVICE_CONTAINER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-database:${POSTGRES_HOST_PORT}/${POSTGRES_DB}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_SERVER_URI=http://moviebox-discovery-service:${MOVIEBOX_DISCOVERY_HOST_PORT}/eureka
    volumes:
      - type: volume
        source: movie-service-cache
        target: /cache
    depends_on:
      - moviebox-discovery-service
      - postgres-database
    restart: on-failure
  postgres-database:
    image: postgres:alpine
    container_name: postgres-database-container
    networks:
      moviebox-network:
    volumes:
       - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - moviebox-discovery-service
    restart: on-failure
  postgres-admin-panel:
    image: dpage/pgadmin4
    container_name: postgres-admin-panel-container
    networks:
      moviebox-network:
    ports:
      - ${POSTGRES_ADMIN_HOST_PORT}:${POSTGRES_ADMIN_CONTAINER_PORT}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_ADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_ADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: on-failure

volumes:
  postgres-data:
    external: true
  pgadmin-data:
    external: true
  movie-service-cache:
    external: true

networks:
  moviebox-network:
    external: true