version: "3.7"

services:
  movie-service:
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    image: movie-service:1.0.0
    container_name: movie-service-container
    networks:
      movie-service-network:
    ports:
      - ${MOVIE_SERVICE_HOST_PORT}:${MOVIE_SERVICE_CONTAINER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-database:${POSTGRES_HOST_PORT}/${POSTGRES_DB}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres-database
  postgres-database:
    image: postgres:alpine
    container_name: postgres-database-container
    networks:
      movie-service-network:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  postgres-admin-panel:
    image: dpage/pgadmin4
    container_name: postgres-admin-panel-container
    networks:
      movie-service-network:
    ports:
      - ${POSTGRES_ADMIN_HOST_PORT}:${POSTGRES_ADMIN_CONTAINER_PORT}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_ADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_ADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/root/.pgadmin
    depends_on:
      - postgres-database

volumes:
  postgres-data:
  pgadmin-data:

networks:
  movie-service-network:
    driver: bridge