spring:
  application:
    name: moviebox-movie-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent_output : true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}
  instance:
    preferIpAddress: true