spring:
  application:
    name: moviebox-movie-service
  datasource:
    url: jdbc:postgresql://postgres-database:5432/movie_db?useSSL=false
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent_output : true