version: "3.7"

services:
  moviebox-discovery-service:
    image: moviebox-discovery
    container_name: moviebox-discovery-container
    ports:
      - ${MOVIEBOX_DISCOVERY_HOST_PORT}:${MOVIEBOX_DISCOVERY_CONTAINER_PORT}